### ISSUE TITLE
Widoco software entity not detected in wikidata

### ISSUE THREAD

**Issue by JB0linches** [SoftwareUnderstanding/SALTbot#2]
Widoco (Q118564029) doesn't have the property instance_of [something that inherits from software category]. Therefore, SALTbot is trying to recreate the software entity, but fails because there is already an entity labelled "Widoco"

**Comment by dgarijo** [comment]
but it was saltbot the entity which added Widoco software to start with...

**Comment by JB0linches** [comment]
It appears it was created by a previous iteration of SALTbot which did not correctly introduce the statement. I introduced by hand the instance of statement in the software entity and it is working now correctly
